"""add due_date and priority to todos

Revision ID: 1581d02841d1
Revises: 2b1a6a841528
Create Date: 2026-06-16 13:33:55.692668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1581d02841d1'
down_revision: Union[str, Sequence[str], None] = '2b1a6a841528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('priority', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'priority')
    op.drop_column('todos', 'due_date')
    # ### end Alembic commands ###
